### ISSUE TITLE
我就。。。

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/rename-back-lnk#1]
奇怪的库又增加了。。。。
你说可不可以搞些更有意义的啊。。。。

**Comment by lingbopro** [comment]
这是实际需求嘛  
怎么能不做呢

**Comment by Minemetero** [comment]
我觉得要做一些大部分人都用的到东西。。。

**Comment by lingbopro** [comment]
> 我觉得要做一些大部分人都用的到东西。。。

emmm

**Comment by lingbopro** [comment]
> 我觉得要做一些大部分人都用的到东西。。。

![Screenshot_20240601_174703.jpg](https://github.com/lingbopro/rename-back-lnk/assets/148617407/3a0fb854-8042-4e21-8877-3bdc0f62316f)

在[一篇文章](https://mp.weixin.qq.com/s/KLU6329pUSK01-8V2zbkcQ)的评论区看到的  
也许可以回答这个问题  
这才是开源的真谛啊（

**Comment by Minemetero** [comment]
支持开源 Forever

**Comment by lingbopro** [comment]
> 支持开源 Forever

此生无悔入开源，来世还做 GitHuber （bushi

**Comment by lingbopro** [comment]
@Minemetero 你快看看easy-github-hosts的新issue，有紧急情况
